### ISSUE TITLE
some kinda error

### ISSUE THREAD

**Issue by Rajbir98** [3ct0s/eclipse-grabber#32]
Traceback (most recent call last):
  File "D:\a\eclipse-grabber\eclipse-grabber\builder.py", line 153, in <module>
    main(get_args())
  File "D:\a\eclipse-grabber\eclipse-grabber\builder.py", line 139, in get_args
    print(start_banner)
  File "D:\a\eclipse-grabber\eclipse-grabber\python3.9.4\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 361-368: character maps to <undefined>

**Comment by 3ct0s** [comment]
I can see that you are not using python 3.8.9 as instructed. The setup script should have automatically installed python 3.8.9. Did you run it using the commands from the instructions?
